-- ============================================================
-- Bahandi esep — network analytics (Prompt C)
-- Applied: 2026-06-28
--
-- Turns 87 stores into a control tower. Heavy aggregation lives in
-- Postgres (security-definer functions called via rpc()) so the Tower
-- never loops over the network client-side. One round trip: the
-- `tower_analytics(p_from, p_to)` RPC returns the whole payload — KPIs
-- + per-store + per-format + per-city + per-cluster — for a window.
--
-- The unexplained-gap signal:
--   gap = theoretical_usage − documented_loss   (clamped ≥ 0)
-- For the demo, `theoretical_usage` is synthesised per store by the
-- seed script into `store_usage_proxy` (so the problem kiosk can be
-- made an obvious outlier). On real Iiko this comes from the OLAP
-- DeletedWithWriteoff feed — the `unexplained_gap` column name stays
-- stable, only the source of `theoretical_usage` swaps.
--
-- Idempotent: safe to re-run on a partially-migrated DB.
-- ============================================================

-- ──────────────────────────────────────────────────────────────
-- 1. store_usage_proxy — synthesised theoretical usage per store
--    (the unexplained-gap source for the demo; replaced by Iiko OLAP
--    in production). One row per store, upserted by the seed script.
-- ──────────────────────────────────────────────────────────────

create table if not exists public.store_usage_proxy (
  store_id           uuid        primary key references public.stores(id) on delete cascade,
  theoretical_usage  numeric     not null check (theoretical_usage >= 0),
  window_days        int         not null check (window_days > 0),
  as_of              date        not null default current_date,
  seeded             boolean     not null default false,
  updated_at         timestamptz not null default now()
);

alter table public.store_usage_proxy enable row level security;

drop policy if exists "store_usage_proxy_select" on public.store_usage_proxy;
create policy "store_usage_proxy_select"
  on public.store_usage_proxy for select
  using ((select auth.role()) = 'authenticated');

drop policy if exists "store_usage_proxy_write_admin" on public.store_usage_proxy;
create policy "store_usage_proxy_write_admin"
  on public.store_usage_proxy for insert
  with check (public.get_my_role() = 'admin');

drop policy if exists "store_usage_proxy_update_admin" on public.store_usage_proxy;
create policy "store_usage_proxy_update_admin"
  on public.store_usage_proxy for update
  using (public.get_my_role() = 'admin')
  with check (public.get_my_role() = 'admin');

drop policy if exists "store_usage_proxy_delete_admin" on public.store_usage_proxy;
create policy "store_usage_proxy_delete_admin"
  on public.store_usage_proxy for delete
  using (public.get_my_role() = 'admin');

-- ──────────────────────────────────────────────────────────────
-- 1b. writeoffs.seeded — tags rows generated by scripts/seed-history.ts
--     so demo data is identifiable. The seed script writes deterministic
--     ids and skips rows that already exist, so re-runs never duplicate
--     (and never break the global audit chain). Idempotent column add.
-- ──────────────────────────────────────────────────────────────
alter table public.writeoffs
  add column if not exists seeded boolean not null default false;

create index if not exists writeoffs_seeded_idx
  on public.writeoffs (seeded) where seeded = true;

-- ──────────────────────────────────────────────────────────────
-- 2. Access guard
--    Analytics must see the WHOLE network (every write-off, every
--    store), but the writeoffs RLS policy hides other submitters'
--    auto_approved rows from reviewers. So the metric functions run
--    SECURITY DEFINER (bypass RLS for reads) and gate entry to
--    reviewer/admin via get_my_role(). Employees get zero rows.
-- ──────────────────────────────────────────────────────────────

-- ──────────────────────────────────────────────────────────────
-- 3. per_store_metrics(p_from, p_to)
--    One row per active store: volume, loss, by-reason breakdown,
--    flagged %, auto-approve rate, avg risk, theoretical usage, and
--    the unexplained_gap proxy. Stores with no write-offs in the
--    window still appear (zeros / null gap) so the leaderboard reads
--    as the whole chain, not just the active slice.
-- ──────────────────────────────────────────────────────────────

create or replace function public.per_store_metrics(
  p_from timestamptz default now() - interval '14 days',
  p_to   timestamptz default now()
) returns table(
  store_id           uuid,
  name               text,
  display_name       text,
  format             store_format,
  city               text,
  city_id            uuid,
  cluster_id         uuid,
  cluster_name       text,
  writeoff_count     bigint,
  total_loss         numeric,
  documented_loss    numeric,
  by_reason          jsonb,
  flagged_count      bigint,
  flagged_pct        numeric,
  auto_approve_count bigint,
  auto_approve_rate  numeric,
  risk_avg           numeric,
  theoretical_usage  numeric,
  unexplained_gap    numeric
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  if public.get_my_role() not in ('reviewer','admin') then
    return;
  end if;

  return query
    with w as (
      select
        w.location_id,
        w.reason_code_id,
        coalesce(w.value_cost, 0)         as value_cost,
        w.risk_score,
        w.status,
        w.iiko_sync_status
      from public.writeoffs w
      where w.created_at >= p_from and w.created_at < p_to
    ),
    by_cat as (
      select w.location_id, rc.category, sum(w.value_cost) as cat_loss
      from w
      left join public.reason_codes rc on rc.id = w.reason_code_id
      group by w.location_id, rc.category
    ),
    reason_json as (
      select location_id, jsonb_object_agg(coalesce(category,'unknown'), cat_loss) as by_reason
      from by_cat
      group by location_id
    ),
    agg as (
      select
        w.location_id,
        count(*)                                                          as writeoff_count,
        sum(w.value_cost)                                                 as total_loss,
        sum(w.value_cost)                                                 as documented_loss,
        count(*) filter (
          where w.status in ('in_review','on_hold','dual_control')
             or w.risk_score >= 15
        )                                                                 as flagged_count,
        count(*) filter (where w.status = 'auto_approved')               as auto_approve_count,
        coalesce(avg(w.risk_score), 0)                                   as risk_avg
      from w
      group by w.location_id
    )
    select
      s.id,
      s.name,
      coalesce(s.display_name, s.name),
      coalesce(s.format, 'street'::store_format),
      s.city,
      s.city_id,
      s.cluster_id,
      sc.name,
      coalesce(agg.writeoff_count, 0),
      coalesce(agg.total_loss, 0),
      coalesce(agg.documented_loss, 0),
      coalesce(rj.by_reason, '{}'::jsonb),
      coalesce(agg.flagged_count, 0),
      case when coalesce(agg.writeoff_count,0) = 0 then 0
           else agg.flagged_count::numeric / agg.writeoff_count end,
      coalesce(agg.auto_approve_count, 0),
      case when coalesce(agg.writeoff_count,0) = 0 then 0
           else agg.auto_approve_count::numeric / agg.writeoff_count end,
      coalesce(agg.risk_avg, 0),
      p.theoretical_usage,
      case when p.theoretical_usage is null then null
           else greatest(p.theoretical_usage - coalesce(agg.documented_loss,0), 0) end
    from public.stores s
    left join agg            on agg.location_id   = s.id
    left join reason_json rj on rj.location_id    = s.id
    left join public.store_clusters sc on sc.id   = s.cluster_id
    left join public.store_usage_proxy p on p.store_id = s.id
    where s.is_active
    order by
      case when p.theoretical_usage is not null
             and greatest(p.theoretical_usage - coalesce(agg.documented_loss,0),0) > 0
           then greatest(p.theoretical_usage - coalesce(agg.documented_loss,0),0)
           else null end desc nulls last,
      coalesce(agg.total_loss, 0) desc,
      s.name;
end;
$$;

revoke execute on function public.per_store_metrics(timestamptz, timestamptz) from anon, public;
grant  execute on function public.per_store_metrics(timestamptz, timestamptz) to authenticated;

-- ──────────────────────────────────────────────────────────────
-- 4. per_format_metrics(p_from, p_to)
--    Format benchmark: loss-per-store + flagged % across formats.
--    The denominator is the active cohort (stores of that format with
--    ≥1 write-off in the window) so the comparison reflects actual
--    loss behaviour per format, not a diluted network average.
-- ──────────────────────────────────────────────────────────────

create or replace function public.per_format_metrics(
  p_from timestamptz default now() - interval '14 days',
  p_to   timestamptz default now()
) returns table(
  format             store_format,
  store_count        bigint,
  network_store_count bigint,
  writeoff_count     bigint,
  total_loss         numeric,
  loss_per_store     numeric,
  flagged_pct        numeric,
  auto_approve_rate  numeric
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  if public.get_my_role() not in ('reviewer','admin') then
    return;
  end if;

  return query
    with w as (
      select w.location_id, coalesce(w.value_cost,0) as value_cost, w.risk_score, w.status
      from public.writeoffs w
      where w.created_at >= p_from and w.created_at < p_to
    ),
    store_fmt as (
      select s.id, coalesce(s.format,'street'::store_format) as fmt
      from public.stores s where s.is_active
    ),
    active_stores as (
      select sf.fmt, count(distinct sf.id) as store_count
      from store_fmt sf
      join w on w.location_id = sf.id
      group by sf.fmt
    ),
    agg as (
      select sf.fmt,
             count(*)                                                          as writeoff_count,
             sum(w.value_cost)                                                 as total_loss,
             count(*) filter (where w.status in ('in_review','on_hold','dual_control') or w.risk_score >= 15) as flagged_count,
             count(*) filter (where w.status = 'auto_approved')               as auto_approve_count
      from w
      join store_fmt sf on sf.id = w.location_id
      group by sf.fmt
    ),
    net as (
      select sf.fmt, count(*) as network_store_count from store_fmt sf group by sf.fmt
    )
    select
      a.fmt,
      coalesce(ast.store_count, 0),
      coalesce(net.network_store_count, 0),
      coalesce(a.writeoff_count, 0),
      coalesce(a.total_loss, 0),
      case when coalesce(ast.store_count,0) = 0 then 0
           else a.total_loss / ast.store_count end,
      case when coalesce(a.writeoff_count,0) = 0 then 0
           else a.flagged_count::numeric / a.writeoff_count end,
      case when coalesce(a.writeoff_count,0) = 0 then 0
           else a.auto_approve_count::numeric / a.writeoff_count end
    from agg a
    left join active_stores ast on ast.fmt = a.fmt
    left join net             on net.fmt   = a.fmt
    order by
      case a.fmt
        when 'kiosk' then 1 when 'mall' then 2 when 'magnum' then 3
        when 'market' then 4 when 'street' then 5 else 99 end;
end;
$$;

revoke execute on function public.per_format_metrics(timestamptz, timestamptz) from anon, public;
grant  execute on function public.per_format_metrics(timestamptz, timestamptz) to authenticated;

-- ──────────────────────────────────────────────────────────────
-- 5. per_city_metrics(p_from, p_to)
--    City rollup. One row per city (all 11), loss + flagged % +
--    store count. Cities with no write-offs in the window appear
--    with zeros so the rollup reads as the whole network.
-- ──────────────────────────────────────────────────────────────

create or replace function public.per_city_metrics(
  p_from timestamptz default now() - interval '14 days',
  p_to   timestamptz default now()
) returns table(
  city               text,
  city_id            uuid,
  store_count        bigint,
  writeoff_count     bigint,
  total_loss         numeric,
  flagged_pct        numeric,
  auto_approve_rate  numeric
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  if public.get_my_role() not in ('reviewer','admin') then
    return;
  end if;

  return query
    with w as (
      select w.location_id, coalesce(w.value_cost,0) as value_cost, w.risk_score, w.status
      from public.writeoffs w
      where w.created_at >= p_from and w.created_at < p_to
    ),
    stores as (
      select s.id, s.city, s.city_id
      from public.stores s where s.is_active
    ),
    agg as (
      select st.city_id,
             count(*)                                                          as writeoff_count,
             sum(w.value_cost)                                                 as total_loss,
             count(*) filter (where w.status in ('in_review','on_hold','dual_control') or w.risk_score >= 15) as flagged_count,
             count(*) filter (where w.status = 'auto_approved')               as auto_approve_count
      from w
      join stores st on st.id = w.location_id
      group by st.city_id
    )
    select
      c.name,
      c.id,
      count(s.id)                                         as store_count,
      coalesce(agg.writeoff_count, 0),
      coalesce(agg.total_loss, 0),
      case when coalesce(agg.writeoff_count,0) = 0 then 0
           else agg.flagged_count::numeric / agg.writeoff_count end,
      case when coalesce(agg.writeoff_count,0) = 0 then 0
           else agg.auto_approve_count::numeric / agg.writeoff_count end
    from public.cities c
    left join stores    s   on s.city_id = c.id
    left join agg           on agg.city_id = c.id
    group by c.id, c.name, agg.writeoff_count, agg.total_loss, agg.flagged_count, agg.auto_approve_count
    order by coalesce(agg.total_loss, 0) desc, c.name;
end;
$$;

revoke execute on function public.per_city_metrics(timestamptz, timestamptz) from anon, public;
grant  execute on function public.per_city_metrics(timestamptz, timestamptz) to authenticated;

-- ──────────────────────────────────────────────────────────────
-- 6. per_cluster_metrics(p_from, p_to)
--    Cluster rollup (City → Cluster → Store). Almaty has 3 clusters;
--    the Tower shows Almaty by its clusters first, then stores.
-- ──────────────────────────────────────────────────────────────

create or replace function public.per_cluster_metrics(
  p_from timestamptz default now() - interval '14 days',
  p_to   timestamptz default now()
) returns table(
  cluster_id         uuid,
  cluster_name       text,
  city_id            uuid,
  city               text,
  store_count        bigint,
  writeoff_count     bigint,
  total_loss         numeric,
  flagged_pct        numeric
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  if public.get_my_role() not in ('reviewer','admin') then
    return;
  end if;

  return query
    with w as (
      select w.location_id, coalesce(w.value_cost,0) as value_cost, w.risk_score, w.status
      from public.writeoffs w
      where w.created_at >= p_from and w.created_at < p_to
    ),
    stores as (
      select s.id, s.cluster_id, s.city_id
      from public.stores s where s.is_active
    ),
    agg as (
      select st.cluster_id,
             count(*)                                                          as writeoff_count,
             sum(w.value_cost)                                                 as total_loss,
             count(*) filter (where w.status in ('in_review','on_hold','dual_control') or w.risk_score >= 15) as flagged_count
      from w
      join stores st on st.id = w.location_id
      group by st.cluster_id
    )
    select
      sc.id,
      sc.name,
      sc.city_id,
      c.name,
      count(s.id)                               as store_count,
      coalesce(agg.writeoff_count, 0),
      coalesce(agg.total_loss, 0),
      case when coalesce(agg.writeoff_count,0) = 0 then 0
           else agg.flagged_count::numeric / agg.writeoff_count end
    from public.store_clusters sc
    left join public.cities  c  on c.id  = sc.city_id
    left join stores         s  on s.cluster_id = sc.id
    left join agg               on agg.cluster_id = sc.id
    group by sc.id, sc.name, sc.city_id, c.name, agg.writeoff_count, agg.total_loss, agg.flagged_count
    order by c.name, sc.name;
end;
$$;

revoke execute on function public.per_cluster_metrics(timestamptz, timestamptz) from anon, public;
grant  execute on function public.per_cluster_metrics(timestamptz, timestamptz) to authenticated;

-- ──────────────────────────────────────────────────────────────
-- 7. network_kpis(p_from, p_to)
--    The top KPI row: total loss, total write-offs, fraud caught
--    (on_hold count + value), recovered value (synced to Iiko), and
--    the network unexplained gap.
-- ──────────────────────────────────────────────────────────────

create or replace function public.network_kpis(
  p_from timestamptz default now() - interval '14 days',
  p_to   timestamptz default now()
) returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  result jsonb;
begin
  if public.get_my_role() not in ('reviewer','admin') then
    return jsonb_build_object(
      'total_loss', 0, 'total_writeoffs', 0, 'fraud_caught_count', 0,
      'fraud_caught_value', 0, 'recovered_value', 0, 'unexplained_gap', 0);
  end if;

  -- Write-off-based KPIs, aggregated once across the window.
  select jsonb_build_object(
    'total_loss',          coalesce(sum(w.value_cost),0),
    'total_writeoffs',     count(*),
    'fraud_caught_count',  count(*) filter (where w.status = 'on_hold'),
    'fraud_caught_value',  coalesce(sum(w.value_cost) filter (where w.status = 'on_hold'),0),
    'recovered_value',     coalesce(sum(w.value_cost) filter (where w.iiko_sync_status = 'synced'),0)
  )
  into result
  from public.writeoffs w
  where w.created_at >= p_from and w.created_at < p_to;

  -- Network unexplained gap: one row per proxied store (theoretical −
  -- documented), never multiplied by write-off count.
  select jsonb_set(
    result,
    '{unexplained_gap}',
    to_jsonb(coalesce((
      select sum(greatest(p.theoretical_usage - sdoc.doc_loss, 0))
      from public.store_usage_proxy p
      cross join lateral (
        select coalesce(sum(w.value_cost),0) as doc_loss
        from public.writeoffs w
        where w.location_id = p.store_id
          and w.created_at >= p_from and w.created_at < p_to
      ) sdoc
      where p.theoretical_usage > sdoc.doc_loss
    ), 0))
  ) into result;

  return result;
end;
$$;

revoke execute on function public.network_kpis(timestamptz, timestamptz) from anon, public;
grant  execute on function public.network_kpis(timestamptz, timestamptz) to authenticated;

-- ──────────────────────────────────────────────────────────────
-- 8. tower_analytics(p_from, p_to)
--    Single round trip: the whole Tower payload (KPIs + per-store +
--    per-format + per-city + per-cluster) as one jsonb document. The
--    page calls this once; everything else is presentation.
-- ──────────────────────────────────────────────────────────────

create or replace function public.tower_analytics(
  p_from timestamptz default now() - interval '14 days',
  p_to   timestamptz default now()
) returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  if public.get_my_role() not in ('reviewer','admin') then
    return jsonb_build_object(
      'kpis', public.network_kpis(p_from, p_to),
      'perStore', '[]'::jsonb,
      'perFormat', '[]'::jsonb,
      'perCity', '[]'::jsonb,
      'perCluster', '[]'::jsonb,
      'from', p_from, 'to', p_to);
  end if;

  return jsonb_build_object(
    'kpis',       public.network_kpis(p_from, p_to),
    'perStore',   coalesce((select jsonb_agg(to_jsonb(t) order by t.unexplained_gap desc nulls last, t.total_loss desc)
                            from public.per_store_metrics(p_from, p_to) t),   '[]'::jsonb),
    'perFormat',  coalesce((select jsonb_agg(to_jsonb(t) order by
                            case t.format when 'kiosk' then 1 when 'mall' then 2 when 'magnum' then 3
                                          when 'market' then 4 when 'street' then 5 else 99 end)
                            from public.per_format_metrics(p_from, p_to) t),  '[]'::jsonb),
    'perCity',    coalesce((select jsonb_agg(to_jsonb(t) order by t.total_loss desc, t.city)
                            from public.per_city_metrics(p_from, p_to) t),    '[]'::jsonb),
    'perCluster', coalesce((select jsonb_agg(to_jsonb(t) order by t.city, t.cluster_name)
                            from public.per_cluster_metrics(p_from, p_to) t),'[]'::jsonb),
    'from', p_from, 'to', p_to
  );
end;
$$;

revoke execute on function public.tower_analytics(timestamptz, timestamptz) from anon, public;
grant  execute on function public.tower_analytics(timestamptz, timestamptz) to authenticated;

comment on table public.store_usage_proxy is
  'Synthesised theoretical usage per store — the unexplained-gap source for the demo (replaced by Iiko OLAP DeletedWithWriteoff in production). Prompt C.';
comment on function public.per_store_metrics(timestamptz, timestamptz) is
  'Per-store network metrics for the control tower (Prompt C). Security definer; reviewer/admin only.';
comment on function public.tower_analytics(timestamptz, timestamptz) is
  'Whole-Tower payload in one round trip (Prompt C). Security definer; reviewer/admin only.';
